import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { logAudit } from '@/lib/services/audit';

export async function GET(request: Request) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const sessionId = searchParams.get('sessionId');

    if (!sessionId) {
      return NextResponse.json({ error: 'Missing sessionId' }, { status: 400 });
    }

    // Check if user is instructor or student.
    // For simplicity, we just check if the session belongs to them OR if they are assigned to the student.
    // Actually, RLS handles `cryptographic_commitments` read access (if we set it up properly), but we can just query it directly.
    const { data: commitment, error } = await supabase
      .from('cryptographic_commitments')
      .select('hash, algorithm, payload_version, created_at')
      .eq('exam_session_id', sessionId)
      .maybeSingle();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    if (!commitment) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 });
    }

    // Transform back to camelCase for the frontend
    const mapped = {
      hash: commitment.hash,
      algorithm: commitment.algorithm,
      payloadVersion: commitment.payload_version,
      timestamp: commitment.created_at,
    };

    return NextResponse.json({ commitment: mapped });

  } catch (error: any) {
    console.error('[API Provenance GET]', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { sessionId, commitment } = body;

    if (!sessionId || !commitment || !commitment.hash) {
      return NextResponse.json({ error: 'Invalid payload' }, { status: 400 });
    }

    // Verify session belongs to the user securely. 
    // An exam session can only have a commitment generated by the student taking it.
    const { data: studentRow } = await supabase
      .from('students')
      .select('id')
      .eq('profile_id', user.id)
      .single();

    if (!studentRow) {
      return NextResponse.json({ error: 'Student not found' }, { status: 403 });
    }

    // Check exam ownership
    const { data: examSession } = await supabase
      .from('exam_sessions')
      .select('id, student_id')
      .eq('id', sessionId)
      .single();

    if (!examSession || examSession.student_id !== studentRow.id) {
      return NextResponse.json({ error: 'Unauthorized session' }, { status: 403 });
    }

    // Upsert commitment
    const { error } = await supabase.from('cryptographic_commitments').upsert({
      exam_session_id: sessionId,
      hash: commitment.hash,
      algorithm: commitment.algorithm,
      payload_version: commitment.payloadVersion,
      created_at: commitment.timestamp || new Date().toISOString(),
    }, { onConflict: 'exam_session_id' });

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    // Audit log
    await logAudit(user.id, 'provenance_created', 'exam_sessions', sessionId, { hash: commitment.hash });

    return NextResponse.json({ success: true });

  } catch (error: any) {
    console.error('[API Provenance POST]', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
